apiVersion: v1
kind: Service
metadata:
  name: register-app-ci
  labels:
    app: register-app-ci
spec:
  selector:
    app: register-app-ci

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
